### ISSUE TITLE
WoWs Info Pro?

### ISSUE THREAD

**Issue by wardylan** [HenryQuan/WoWs-Info-Re#42]
The latest version on app store was always asking me to upgrade to pro but there was no upgrade option shown after I press the "UPGRADE TO PRO" button.

**Comment by HenryQuan** [comment]
Thanks for the issue.
Unfortunately, there seems to be some issues on the Apple side and I cannot do anything about that. Please wait patiently.

**Comment by HenryQuan** [comment]
I just received an email from Apple. Currently, I am preparing for a new update in order to resolve this issue.

**Comment by wardylan** [comment]
Thanks, I'm waiting for the update.

**Comment by HenryQuan** [comment]
I have received an email from Apple that it has been approved.
